version: 0.2

phases:
  install:
    commands:
      - echo Install node 13...
      - curl -sL https://deb.nodesource.com/setup_13.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Install dependencies...
      - install
  build:
    commands:
      # test
      echo Building...
      npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
